# Generated by Django 5.1.7 on 2025-04-04 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_produto_estoque'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='avaliacao',
            field=models.CharField(default='Sem avaliação', max_length=200, verbose_name='Avaliação'),
        ),
        migrations.AddField(
            model_name='produto',
            name='nota',
            field=models.IntegerField(default=0, verbose_name='Nota'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Preço'),
        ),
    ]
