# Generated by Django 5.1.7 on 2025-04-08 01:39

import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_produto_avaliacao_produto_nota_alter_produto_preco'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Modificado')),
                ('ativo', models.BooleanField(default=True)),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('email', models.EmailField(blank=True, max_length=100, verbose_name='Email')),
                ('assunto', models.CharField(max_length=120, verbose_name='Assunto')),
                ('mensagem', models.TextField(max_length=400, verbose_name='Mensagem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='produto',
            name='avaliacao',
            field=models.CharField(default=None, max_length=400, verbose_name='Avaliação'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=stdimage.models.StdImageField(force_min_size=False, upload_to='produtos', variations={'thumb': {'height': 124, 'width': 124}}, verbose_name='Imagem'),
        ),
    ]
